settings:
  title: 'overfitted.io status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: overfitted-io
    name: overfitted.io
    url: 'https://overfitted.io/'
    method: GET
    expectStatus: 200
  - id: db-api
    name: Database API
    url: 'https://db-api.api.overfitted.io/health-check'
    method: GET
    expectStatus: 200
  - id: glyph-api
    name: Glyph API
    url: 'https://glyph.api.overfitted.io/health-check'
    method: GET
    expectStatus: 200
  - id: template-parser-api
    name: Template Parser API
    url: 'https://template-parser.api.overfitted.io/health-check'
    method: GET
    expectStatus: 200
